In [6]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [7]:
%cd /content/drive/MyDrive/Dibimbing/Day 7 - Data Cleaning

/content/drive/MyDrive/Dibimbing/Day 7 - Data Cleaning

In [8]:
%ls

 DataCLeansing_module_v2_students.ipynb
'Day 7 - Data Cleansing_v2.pdf'
'Hands-on Day 7 - Data Cleansing(In class).ipynb'
 Sales-Export_2021-2022_Details.gsheet
 Sales-Export_2021-2022_Details.xlsx
 telco_customer_churn.csv

In [9]:
import pandas as pd

# Task 1 - Load Data to DataFrame

In [10]:
df = pd.read_csv('telco_customer_churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [11]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [12]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [13]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [14]:
df.shape

(7043, 21)

# Task 2 - Show data types for all columns

In [15]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

# Task 3 - Rename Column

## 3a. Rename customerID to CustID

In [16]:
df = df.rename(columns={'customerID':'CustID'})
df.columns

Index(['CustID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [17]:
df

,CustID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

## 3b. Rename all columns to lowercase

In [18]:
df.columns = df.columns.str.lower()
df.columns

Index(['custid', 'gender', 'seniorcitizen', 'partner', 'dependents', 'tenure',
       'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity',
       'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv',
       'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod',
       'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [19]:
df

,custid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# Task 4 - Remove "(automatic)" from the paymentmethod column value and no spaces at the beginning or end

In [20]:
df['paymentmethod']

0                Electronic check
1                    Mailed check
2                    Mailed check
3       Bank transfer (automatic)
4                Electronic check
                  ...
7038                 Mailed check
7039      Credit card (automatic)
7040             Electronic check
7041                 Mailed check
7042    Bank transfer (automatic)
Name: paymentmethod, Length: 7043, dtype: object

In [21]:
df['paymentmethod'] = df['paymentmethod'].str.replace('automatic','')
df['paymentmethod']

0       Electronic check
1           Mailed check
2           Mailed check
3       Bank transfer ()
4       Electronic check
              ...
7038        Mailed check
7039      Credit card ()
7040    Electronic check
7041        Mailed check
7042    Bank transfer ()
Name: paymentmethod, Length: 7043, dtype: object

In [22]:
df['paymentmethod'] = df['paymentmethod'].str.replace('()','', regex = False)
df['paymentmethod']

0       Electronic check
1           Mailed check
2           Mailed check
3         Bank transfer
4       Electronic check
              ...
7038        Mailed check
7039        Credit card
7040    Electronic check
7041        Mailed check
7042      Bank transfer
Name: paymentmethod, Length: 7043, dtype: object

In [35]:
df['paymentmethod'] = df['paymentmethod'].str.strip()
df['paymentmethod']

0       Electronic check
1           Mailed check
2           Mailed check
3          Bank transfer
4       Electronic check
              ...
7038        Mailed check
7039         Credit card
7040    Electronic check
7041        Mailed check
7042       Bank transfer
Name: paymentmethod, Length: 7043, dtype: object

# Task 5 - Data Preprocessing

## 5a. One-hot encoding for the phoneservice column with prefix 'service'

In [23]:
df['phoneservice']

0        No
1       Yes
2       Yes
3        No
4       Yes
       ...
7038    Yes
7039    Yes
7040     No
7041    Yes
7042    Yes
Name: phoneservice, Length: 7043, dtype: object

In [24]:
df_phoneservice = df['phoneservice']

In [25]:
pd.get_dummies(df_phoneservice, columns=['phoneservice'], prefix='service')

      service_No  service_Yes
0              1            0
1              0            1
2              0            1
3              1            0
4              0            1
...          ...          ...
7038           0            1
7039           0            1
7040           1            0
7041           0            1
7042           0            1

[7043 rows x 2 columns]

## 5b. Normalization for monthlycharges

In [26]:
df['monthlycharges']

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: monthlycharges, Length: 7043, dtype: float64

In [27]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
df['monthlycharges'] = min_max_scaler.fit_transform(df[['monthlycharges']])
df['monthlycharges']

0       0.115423
1       0.385075
2       0.354229
3       0.239303
4       0.521891
          ...
7038    0.662189
7039    0.845274
7040    0.112935
7041    0.558706
7042    0.869652
Name: monthlycharges, Length: 7043, dtype: float64

## 5c. Standardization for totalcharges

In [28]:
df['totalcharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: totalcharges, Length: 7043, dtype: object

In [29]:
def isnumber(x):
  try:
    float(x)
    return True
  except:
    return False
df['isnumber'] = df['totalcharges'].apply(isnumber)
df['isnumber']

0       True
1       True
2       True
3       True
4       True
        ...
7038    True
7039    True
7040    True
7041    True
7042    True
Name: isnumber, Length: 7043, dtype: bool

In [30]:
index_notnumber =  df[~df['isnumber']].index
index_notnumber

Int64Index([488, 753, 936, 1082, 1340, 3331, 3826, 4380, 5218, 6670, 6754], dtype='int64')

In [31]:
median = df[df['isnumber']]['totalcharges'].astype('float64').median()
median

1397.475

In [32]:
df.loc[index_notnumber,'totalcharges'] = median

In [33]:
df.loc[index_notnumber]['totalcharges']

488     1397.475
753     1397.475
936     1397.475
1082    1397.475
1340    1397.475
3331    1397.475
3826    1397.475
4380    1397.475
5218    1397.475
6670    1397.475
6754    1397.475
Name: totalcharges, dtype: object

In [34]:
df['totalcharges'].astype('float64')

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: totalcharges, Length: 7043, dtype: float64

In [35]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
df['totalcharges'] = std_scaler.fit_transform(df[['totalcharges']])
df['totalcharges']

0      -0.994242
1      -0.173244
2      -0.959674
3      -0.194766
4      -0.940470
          ...
7038   -0.128655
7039    2.243151
7040   -0.854469
7041   -0.872062
7042    2.014288
Name: totalcharges, Length: 7043, dtype: float64